console.log("Hello World!!!");
console.log('Hello World!!!');
console.log("    Have \n    A\n    Nice\n    Day\n");
var a = 10;
console.log("Value of a is " + a);
var a;
a = 20;
console.log("Value of a is " + a);
var s1 = "keerthi";
console.log("Value of s1 is " + s1);
var s1;
s1 = 'aruna';
console.log("Value of s1 is " + s1);
var t = true;
console.log("Value of t is " + t);
var t;
t = false;
console.log("Value of t is " + t);
var b; //data type as well as value
b = null;
console.log("Value of b is " + b);
var s;
console.log("value of s is " + s);
